# Aggregation Queries

Queries using aggregation functions, `GROUP BY`, and `HAVING` clauses. Using `LEFT JOIN` in combination with `GROUP BY`

In [1]:
import json
import pymysql 

pymysql.install_as_MySQLdb()

with open('cred.json') as f:
    creds = json.load(f)

connection_string = "mysql://{user}:{password}@{host}".format(**creds)

In [2]:
%load_ext sql
%config SqlMagic.autocommit=True
%sql $connection_string

'Connected: dimitri@None'

### Increasing complexity of queries

In [3]:
%%sql

USE shared_sales

 * mysql://dimitri:***@db.data-science-ust.net
0 rows affected.

[]

## Aggregation functions MAX, MIN, AVG, SUM, COUNT

In [4]:
%%sql

SELECT MAX(RetailPrice) as max_price, AVG(RetailPrice) as avg_price 
FROM products

 * mysql://dimitri:***@db.data-science-ust.net
1 rows affected.

[(Decimal('1800.00'), Decimal('196.033500'))]

In [5]:
%%sql

SELECT ProductNumber, MAX(RetailPrice) as max_price, AVG(RetailPrice) as avg_price 
FROM products

 * mysql://dimitri:***@db.data-science-ust.net
1 rows affected.

[(1, Decimal('1800.00'), Decimal('196.033500'))]

In [6]:
%%sql

-- aggregation with condition

SELECT avg(RetailPrice) avg_price 
FROM products 
WHERE CategoryID IN (
    SELECT CategoryID 
    FROM categories
    WHERE CategoryDescription = "Bikes")

 * mysql://dimitri:***@db.data-science-ust.net
1 rows affected.

[(Decimal('1321.250000'),)]

In [7]:
%%sql

-- what not to do:

SELECT *
FROM products
GROUP BY CategoryID

 * mysql://dimitri:***@db.data-science-ust.net
6 rows affected.

[(3, 'Dog Ear Cyclecomputer', None, Decimal('75.00'), 20, 1),
 (1, 'Trek 9000 Mountain Bike', None, Decimal('1200.00'), 6, 2),
 (23, 'Ultra-Pro Rain Jacket', None, Decimal('85.00'), 30, 3),
 (4, 'Victoria Pro All Weather Tires', None, Decimal('54.95'), 20, 4),
 (39, 'Road Warrior Hitch Pack', None, Decimal('175.00'), 6, 5),
 (27, 'X-Pro All Weather Tires', None, Decimal('24.00'), 20, 6)]

In [8]:
%%sql

SELECT CategoryID, AVG(RetailPrice) as avg_price
FROM products
GROUP BY CategoryID

 * mysql://dimitri:***@db.data-science-ust.net
6 rows affected.

[(1, Decimal('66.191667')),
 (2, Decimal('1321.250000')),
 (3, Decimal('51.250000')),
 (4, Decimal('79.765556')),
 (5, Decimal('177.500000')),
 (6, Decimal('29.000000'))]

In [9]:
%%sql 

-- using in a subquery

SELECT * FROM (
    SELECT CategoryID, AVG(RetailPrice) as avg_price
    FROM products
    GROUP BY CategoryID) as q NATURAL JOIN categories

 * mysql://dimitri:***@db.data-science-ust.net
6 rows affected.

[(1, Decimal('66.191667'), 'Accessories'),
 (2, Decimal('1321.250000'), 'Bikes'),
 (3, Decimal('51.250000'), 'Clothing'),
 (4, Decimal('79.765556'), 'Components'),
 (5, Decimal('177.500000'), 'Car racks'),
 (6, Decimal('29.000000'), 'Tires')]

In [10]:
%%sql

SELECT CategoryID, AVG(RetailPrice) as avg_price
FROM products
GROUP BY CategoryID
HAVING avg_price > 100

 * mysql://dimitri:***@db.data-science-ust.net
2 rows affected.

[(2, Decimal('1321.250000')), (5, Decimal('177.500000'))]

In [11]:
%%sql

SELECT * FROM (
    SELECT CategoryID, AVG(RetailPrice) as avg_price
    FROM products
    GROUP BY CategoryID
) as q WHERE avg_price > 100

 * mysql://dimitri:***@db.data-science-ust.net
2 rows affected.

[(2, Decimal('1321.250000')), (5, Decimal('177.500000'))]

In [12]:
%%sql

select * from products
WHERE RetailPrice > 100

 * mysql://dimitri:***@db.data-science-ust.net
13 rows affected.

[(1, 'Trek 9000 Mountain Bike', None, Decimal('1200.00'), 6, 2),
 (2, 'Eagle FS-3 Mountain Bike', None, Decimal('1800.00'), 8, 2),
 (6, 'Viscount Mountain Bike', None, Decimal('635.00'), 5, 2),
 (11, 'GT RTS-2 Mountain Bike', None, Decimal('1650.00'), 5, 2),
 (14, 'Eagle SA-120 Clipless Pedals', None, Decimal('139.95'), 20, 4),
 (18, 'Viscount CardioSport Sport Watch', None, Decimal('179.00'), 12, 1),
 (25, 'King Cobra Helmet', None, Decimal('139.00'), 30, 1),
 (26, 'Glide-O-Matic Cycling Helmet', None, Decimal('125.00'), 24, 1),
 (36, 'Cosmic Elite Road Warrior Wheels', None, Decimal('165.00'), 22, 4),
 (37, 'AeroFlo ATB Wheels', None, Decimal('189.00'), 40, 4),
 (38, 'Cycle-Doc Pro Repair Stand', None, Decimal('166.00'), 12, 1),
 (39, 'Road Warrior Hitch Pack', None, Decimal('175.00'), 6, 5),
 (40, 'Ultimate Export 2G Car Rack', None, Decimal('180.00'), 8, 5)]

In [13]:
%%sql

SELECT * 
FROM orders 
WHERE OrderNumber NOT IN (
    SELECT OrderNumber 
    FROM order_details)

 * mysql://dimitri:***@db.data-science-ust.net
11 rows affected.

[(198, datetime.date(2017, 10, 8), datetime.date(2017, 10, 10), 1002, 703),
 (216, datetime.date(2017, 10, 12), datetime.date(2017, 10, 12), 1016, 707),
 (305, datetime.date(2017, 11, 1), datetime.date(2017, 11, 5), 1013, 708),
 (361, datetime.date(2017, 11, 12), datetime.date(2017, 11, 13), 1016, 706),
 (484, datetime.date(2017, 12, 9), datetime.date(2017, 12, 10), 1021, 707),
 (523, datetime.date(2017, 12, 15), datetime.date(2017, 12, 17), 1003, 704),
 (629, datetime.date(2018, 1, 8), datetime.date(2018, 1, 12), 1014, 704),
 (632, datetime.date(2018, 1, 8), datetime.date(2018, 1, 12), 1001, 706),
 (689, datetime.date(2018, 1, 15), datetime.date(2018, 1, 16), 1015, 705),
 (753, datetime.date(2018, 1, 28), datetime.date(2018, 1, 30), 1013, 701),
 (816, datetime.date(2018, 2, 9), datetime.date(2018, 2, 12), 1011, 701)]

In [14]:
%%sql

SELECT * FROM orders  NATURAL LEFT JOIN order_details

 * mysql://dimitri:***@db.data-science-ust.net
3984 rows affected.

[(1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 1, Decimal('1200.00'), 2),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 6, Decimal('635.00'), 3),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 11, Decimal('1650.00'), 4),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 16, Decimal('28.00'), 1),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 21, Decimal('55.00'), 3),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 26, Decimal('121.25'), 5),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 40, Decimal('174.60'), 6),
 (2, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1001, 703, 27, Decimal('24.00'), 4),
 (2, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1001, 703, 40, Decimal('180.00'), 4),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 1, Decimal('1164.00'), 5),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 6, Decimal('615.95'), 5),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 11, Decimal('1650.00'), 1),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 16, Decimal('28.00'), 2),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 21, Decimal('55.00'), 3),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 26, Decimal('125.00'), 3),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 31, Decimal('21.34'), 5),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 36, Decimal('165.00'), 4),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 1, Decimal('1200.00'), 4),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 9, Decimal('33.00'), 3),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 17, Decimal('45.00'), 1),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 25, Decimal('134.83'), 6),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 39, Decimal('169.75'), 5),
 (5, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1024, 708, 1, Decimal('1200.00'), 4),
 (5, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1024, 708, 14, Decimal('135.75'), 5),
 (5, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1024, 708, 31, Decimal('22.00'), 3),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 2, Decimal('1746.00'), 5),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 7, Decimal('49.00'), 2),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 12, Decimal('22.80'), 6),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 17, Decimal('43.65'), 5),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 22, Decimal('79.54'), 6),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 27, Decimal('24.00'), 4),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 32, Decimal('32.00'), 2),
 (7, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1001, 708, 14, Decimal('139.95'), 3),
 (7, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1001, 708, 27, Decimal('24.00'), 2),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 16, Decimal('28.00'), 2),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 22, Decimal('82.00'), 3),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 28, Decimal('29.00'), 4),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 34, Decimal('27.00'), 1),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 40, Decimal('174.60'), 6),
 (9, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1007, 708, 24, Decimal('69.00'), 1),
 (10, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1012, 701, 1, Decimal('1200.00'), 2),
 (10, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1012, 701, 24, Decimal('69.00'), 3),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 1, Decimal('1200.00'), 1),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 6, Decimal('615.95'), 6),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 11, Decimal('1650.00'), 3),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 16, Decimal('28.00'), 1),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 21, Decimal('55.00'), 3),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 26, Decimal('125.00'), 1),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 31, Decimal('21.34'), 5),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 36, Decimal('160.05'), 5),
 (12, datetime.date(2017, 9, 3), datetime.date(2017, 9, 6), 1024, 706, 10, Decimal('36.00'), 2),
 (13, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1024, 704, 1, Decimal('1200.00'), 2),
 (13, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1024, 704, 11, Decimal('1650.00'), 3),
 (13, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1024, 704, 28, Decimal('29.00'), 1),
 (13, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1024, 704, 38, Decimal('166.00'), 1),
 (14, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1013, 704, 1, Decimal('1164.00'), 5),
 (14, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1013, 704, 14, Decimal('139.95'), 2),
 (14, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1013, 704, 40, Decimal('180.00'), 4),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 1, Decimal('1200.00'), 2),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 9, Decimal('33.00'), 3),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 17, Decimal('43.65'), 5),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 29, Decimal('34.00'), 2),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 37, Decimal('189.00'), 1),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 9, Decimal('33.00'), 1),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 14, Decimal('139.95'), 2),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 19, Decimal('47.00'), 3),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 24, Decimal('69.00'), 4),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 29, Decimal('34.00'), 3),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 34, Decimal('26.19'), 6),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 39, Decimal('169.75'), 6),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 1, Decimal('1200.00'), 2),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 7, Decimal('47.53'), 6),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 13, Decimal('65.47'), 5),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 19, Decimal('47.00'), 4),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 25, Decimal('134.83'), 5),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 36, Decimal('160.05'), 6),
 (18, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1016, 708, 12, Decimal('22.80'), 6),
 (18, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1016, 708, 20, Decimal('15.00'), 4),
 (18, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1016, 708, 28, Decimal('29.00'), 4),
 (18, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1016, 708, 36, Decimal('165.00'), 3),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 1, Decimal('1164.00'), 5),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 6, Decimal('635.00'), 2),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 11, Decimal('1650.00'), 4),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 20, Decimal('15.00'), 3),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 25, Decimal('139.00'), 3),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 30, Decimal('45.00'), 4),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 35, Decimal('37.83'), 6),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 40, Decimal('180.00'), 4),
 (20, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1011, 706, 1, Decimal('1200.00'), 3),
 (20, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1011, 706, 37, Decimal('183.33'), 6),
 (21, datetime.date(2017, 9, 4), datetime.date(2017, 9, 4), 1014, 702, 3, Decimal('75.00'), 3),
 (21, datetime.date(2017, 9, 4), datetime.date(2017, 9, 4), 1014, 702, 13, Decimal('65.47'), 6),
 (21, datetime.date(2017, 9, 4), datetime.date(2017, 9, 4), 1014, 702, 33, Decimal('18.43'), 5),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 1, Decimal('1164.00'), 5),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 7, Decimal('47.53'), 6),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 17, Decimal('45.00'), 2),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 29, Decimal('34.00'), 1),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 35, Decimal('37.83'), 6),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 1, Decimal('1164.00'), 6),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 6, Decimal('635.00'), 3),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 11, Decimal('1650.00'), 4),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 16, Decimal('27.16'), 6),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 21, Decimal('55.00'), 3),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 29, Decimal('34.00'), 1),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 34, Decimal('26.19'), 5),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 39, Decimal('175.00'), 2),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 9, Decimal('33.00'), 2),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 14, Decimal('139.95'), 3),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 19, Decimal('47.00'), 4),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 24, Decimal('69.00'), 1),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 29, Decimal('34.00'), 2),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 34, Decimal('27.00'), 2),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 1, Decimal('1200.00'), 4),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 11, Decimal('1650.00'), 3),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 17, Decimal('45.00'), 3),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 29, Decimal('34.00'), 2),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 35, Decimal('37.83'), 5),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 1, Decimal('1164.00'), 5),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 7, Decimal('47.53'), 6),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 13, Decimal('67.50'), 3),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 24, Decimal('69.00'), 1),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 30, Decimal('45.00'), 2),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 36, Decimal('160.05'), 5),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 1, Decimal('1164.00'), 6),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 7, Decimal('49.00'), 3),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 13, Decimal('67.50'), 1),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 26, Decimal('121.25'), 5),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 32, Decimal('32.00'), 1),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 38, Decimal('166.00'), 1),
 (28, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1004, 703, 7, Decimal('49.00'), 4),
 (28, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1004, 703, 27, Decimal('23.28'), 6),
 (29, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1015, 707, 38, Decimal('166.00'), 4),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 1, Decimal('1164.00'), 5),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 9, Decimal('33.00'), 1),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 17, Decimal('45.00'), 4),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 29, Decimal('34.00'), 4),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 37, Decimal('183.33'), 6),
 (31, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1014, 701, 16, Decimal('27.16'), 6),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 1, Decimal('1164.00'), 6),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 7, Decimal('49.00'), 1),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 19, Decimal('45.59'), 5),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 25, Decimal('134.83'), 6),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 31, Decimal('21.34'), 5),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 37, Decimal('189.00'), 3),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 1, Decimal('1200.00'), 1),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 7, Decimal('47.53'), 6),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 13, Decimal('65.47'), 5),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 19, Decimal('47.00'), 4),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 33, Decimal('19.00'), 1),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 39, Decimal('175.00'), 2),
 (34, datetime.date(2017, 9, 7), datetime.date(2017, 9, 8), 1010, 705, 8, Decimal('48.50'), 5),
 (34, datetime.date(2017, 9, 7), datetime.date(2017, 9, 8), 1010, 705, 28, Decimal('28.13'), 6),
 (35, datetime.date(2017, 9, 7), datetime.date(2017, 9, 7), 1012, 701, 1, Decimal('1200.00'), 4),
 (35, datetime.date(2017, 9, 7), datetime.date(2017, 9, 7), 1012, 701, 14, Decimal('139.95'), 1),
 (35, datetime.date(2017, 9, 7), datetime.date(2017, 9, 7), 1012, 701, 32, Decimal('31.04'), 5),
 (36, datetime.date(2017, 9, 7), datetime.date(2017, 9, 8), 1007, 705, 5, Decimal('7.45'), 1),
 (37, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1027, 702, 8, Decimal('50.00'), 3),
 (37, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1027, 702, 18, Decimal('173.63'), 6),
 (37, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1027, 702, 28, Decimal('29.00'), 1),
 (37, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1027, 702, 38, Decimal('166.00'), 3),
 (38, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1017, 702, 39, Decimal('175.00'), 4),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 1, Decimal('1164.00'), 6),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 6, Decimal('615.95'), 5),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 11, Decimal('1600.50'), 6),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 16, Decimal('28.00'), 2),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 21, Decimal('55.00'), 3),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 26, Decimal('125.00'), 1),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 31, Decimal('22.00'), 2),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 36, Decimal('165.00'), 1),
 (40, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1017, 703, 6, Decimal('635.00'), 1),
 (40, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1017, 703, 19, Decimal('45.59'), 5),
 (40, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1017, 703, 32, Decimal('31.04'), 5),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 10, Decimal('36.00'), 4),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 16, Decimal('27.16'), 5),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 22, Decimal('79.54'), 5),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 28, Decimal('28.13'), 6),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 34, Decimal('26.19'), 6),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 40, Decimal('180.00'), 4),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 1, Decimal('1164.00'), 5),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 9, Decimal('33.00'), 1),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 19, Decimal('47.00'), 3),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 27, Decimal('24.00'), 1),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 35, Decimal('39.00'), 4),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 1, Decimal('1200.00'), 2),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 6, Decimal('635.00'), 3),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 11, Decimal('1650.00'), 1),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 16, Decimal('27.16'), 5),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 28, Decimal('28.13'), 6),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 33, Decimal('19.00'), 4),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 38, Decimal('161.02'), 5),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 1, Decimal('1200.00'), 1),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 7, Decimal('49.00'), 1),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 13, Decimal('67.50'), 1),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 26, Decimal('121.25'), 6),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 32, Decimal('31.04'), 5),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 38, Decimal('166.00'), 1),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 1, Decimal('1164.00'), 5),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 6, Decimal('635.00'), 2),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 11, Decimal('1600.50'), 6),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 16, Decimal('28.00'), 3),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 25, Decimal('139.00'), 3),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 30, Decimal('43.65'), 5),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 35, Decimal('39.00'), 3),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 40, Decimal('180.00'), 2),
 (46, datetime.date(2017, 9, 9), datetime.date(2017, 9, 10), 1018, 707, 35, Decimal('39.00'), 2),

In [15]:
%%sql

-- bad because mixes aggregated and random 

SELECT * FROM orders  NATURAL LEFT JOIN order_details
GROUP BY OrderNumber

 * mysql://dimitri:***@db.data-science-ust.net
944 rows affected.

[(1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 1, Decimal('1200.00'), 2),
 (2, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1001, 703, 27, Decimal('24.00'), 4),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 1, Decimal('1164.00'), 5),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 1, Decimal('1200.00'), 4),
 (5, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1024, 708, 1, Decimal('1200.00'), 4),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 2, Decimal('1746.00'), 5),
 (7, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1001, 708, 14, Decimal('139.95'), 3),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 16, Decimal('28.00'), 2),
 (9, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1007, 708, 24, Decimal('69.00'), 1),
 (10, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1012, 701, 1, Decimal('1200.00'), 2),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 1, Decimal('1200.00'), 1),
 (12, datetime.date(2017, 9, 3), datetime.date(2017, 9, 6), 1024, 706, 10, Decimal('36.00'), 2),
 (13, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1024, 704, 1, Decimal('1200.00'), 2),
 (14, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1013, 704, 1, Decimal('1164.00'), 5),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 1, Decimal('1200.00'), 2),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 9, Decimal('33.00'), 1),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 1, Decimal('1200.00'), 2),
 (18, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1016, 708, 12, Decimal('22.80'), 6),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 1, Decimal('1164.00'), 5),
 (20, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1011, 706, 1, Decimal('1200.00'), 3),
 (21, datetime.date(2017, 9, 4), datetime.date(2017, 9, 4), 1014, 702, 3, Decimal('75.00'), 3),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 1, Decimal('1164.00'), 5),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 1, Decimal('1164.00'), 6),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 9, Decimal('33.00'), 2),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 1, Decimal('1200.00'), 4),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 1, Decimal('1164.00'), 5),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 1, Decimal('1164.00'), 6),
 (28, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1004, 703, 7, Decimal('49.00'), 4),
 (29, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1015, 707, 38, Decimal('166.00'), 4),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 1, Decimal('1164.00'), 5),
 (31, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1014, 701, 16, Decimal('27.16'), 6),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 1, Decimal('1164.00'), 6),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 1, Decimal('1200.00'), 1),
 (34, datetime.date(2017, 9, 7), datetime.date(2017, 9, 8), 1010, 705, 8, Decimal('48.50'), 5),
 (35, datetime.date(2017, 9, 7), datetime.date(2017, 9, 7), 1012, 701, 1, Decimal('1200.00'), 4),
 (36, datetime.date(2017, 9, 7), datetime.date(2017, 9, 8), 1007, 705, 5, Decimal('7.45'), 1),
 (37, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1027, 702, 8, Decimal('50.00'), 3),
 (38, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1017, 702, 39, Decimal('175.00'), 4),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 1, Decimal('1164.00'), 6),
 (40, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1017, 703, 6, Decimal('635.00'), 1),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 10, Decimal('36.00'), 4),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 1, Decimal('1164.00'), 5),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 1, Decimal('1200.00'), 2),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 1, Decimal('1200.00'), 1),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 1, Decimal('1164.00'), 5),
 (46, datetime.date(2017, 9, 9), datetime.date(2017, 9, 10), 1018, 707, 35, Decimal('39.00'), 2),
 (47, datetime.date(2017, 9, 9), datetime.date(2017, 9, 11), 1023, 708, 1, Decimal('1164.00'), 5),
 (48, datetime.date(2017, 9, 9), datetime.date(2017, 9, 12), 1004, 707, 1, Decimal('1200.00'), 1),
 (49, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1015, 704, 13, Decimal('67.50'), 3),
 (50, datetime.date(2017, 9, 9), datetime.date(2017, 9, 13), 1002, 704, 5, Decimal('7.45'), 2),
 (51, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1018, 707, 1, Decimal('1200.00'), 1),
 (52, datetime.date(2017, 9, 10), datetime.date(2017, 9, 12), 1001, 701, 30, Decimal('43.65'), 6),
 (53, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 706, 1, Decimal('1164.00'), 6),
 (54, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1007, 707, 10, Decimal('36.00'), 2),
 (55, datetime.date(2017, 9, 10), datetime.date(2017, 9, 12), 1001, 707, 10, Decimal('36.00'), 1),
 (56, datetime.date(2017, 9, 10), datetime.date(2017, 9, 13), 1014, 702, 6, Decimal('635.00'), 4),
 (57, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 703, 1, Decimal('1200.00'), 2),
 (58, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1006, 701, 1, Decimal('1200.00'), 2),
 (59, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 704, 1, Decimal('1200.00'), 4),
 (60, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1013, 708, 1, Decimal('1200.00'), 1),
 (61, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 706, 1, Decimal('1200.00'), 3),
 (62, datetime.date(2017, 9, 11), datetime.date(2017, 9, 14), 1003, 703, 7, Decimal('49.00'), 3),
 (63, datetime.date(2017, 9, 11), datetime.date(2017, 9, 14), 1023, 708, 1, Decimal('1164.00'), 6),
 (64, datetime.date(2017, 9, 11), datetime.date(2017, 9, 15), 1027, 708, 1, Decimal('1200.00'), 1),
 (65, datetime.date(2017, 9, 11), datetime.date(2017, 9, 14), 1021, 703, 1, Decimal('1200.00'), 3),
 (66, datetime.date(2017, 9, 11), datetime.date(2017, 9, 12), 1026, 703, 1, Decimal('1200.00'), 1),
 (67, datetime.date(2017, 9, 11), datetime.date(2017, 9, 12), 1025, 702, 10, Decimal('36.00'), 4),
 (68, datetime.date(2017, 9, 12), datetime.date(2017, 9, 13), 1027, 702, 19, Decimal('45.59'), 6),
 (69, datetime.date(2017, 9, 12), datetime.date(2017, 9, 14), 1021, 705, 6, Decimal('635.00'), 3),
 (70, datetime.date(2017, 9, 13), datetime.date(2017, 9, 17), 1016, 706, 9, Decimal('32.01'), 5),
 (71, datetime.date(2017, 9, 13), datetime.date(2017, 9, 15), 1016, 708, 1, Decimal('1200.00'), 1),
 (72, datetime.date(2017, 9, 13), datetime.date(2017, 9, 17), 1003, 708, 16, Decimal('27.16'), 5),
 (73, datetime.date(2017, 9, 13), datetime.date(2017, 9, 16), 1005, 705, 1, Decimal('1164.00'), 5),
 (74, datetime.date(2017, 9, 13), datetime.date(2017, 9, 14), 1002, 703, 1, Decimal('1200.00'), 2),
 (75, datetime.date(2017, 9, 13), datetime.date(2017, 9, 15), 1014, 706, 1, Decimal('1200.00'), 4),
 (76, datetime.date(2017, 9, 13), datetime.date(2017, 9, 16), 1012, 703, 18, Decimal('173.63'), 5),
 (77, datetime.date(2017, 9, 13), datetime.date(2017, 9, 14), 1008, 706, 1, Decimal('1200.00'), 1),
 (78, datetime.date(2017, 9, 14), datetime.date(2017, 9, 17), 1007, 701, 1, Decimal('1200.00'), 3),
 (79, datetime.date(2017, 9, 14), datetime.date(2017, 9, 18), 1006, 703, 1, Decimal('1164.00'), 6),
 (80, datetime.date(2017, 9, 14), datetime.date(2017, 9, 17), 1025, 708, 1, Decimal('1200.00'), 3),
 (81, datetime.date(2017, 9, 14), datetime.date(2017, 9, 14), 1006, 705, 39, Decimal('169.75'), 6),
 (82, datetime.date(2017, 9, 14), datetime.date(2017, 9, 17), 1005, 701, 1, Decimal('1164.00'), 6),
 (83, datetime.date(2017, 9, 14), datetime.date(2017, 9, 17), 1021, 708, 10, Decimal('36.00'), 4),
 (84, datetime.date(2017, 9, 14), datetime.date(2017, 9, 14), 1022, 707, 16, Decimal('27.16'), 6),
 (85, datetime.date(2017, 9, 14), datetime.date(2017, 9, 16), 1015, 705, 16, Decimal('28.00'), 2),
 (86, datetime.date(2017, 9, 14), datetime.date(2017, 9, 17), 1009, 701, 1, Decimal('1200.00'), 2),
 (87, datetime.date(2017, 9, 14), datetime.date(2017, 9, 15), 1002, 704, 1, Decimal('1164.00'), 5),
 (88, datetime.date(2017, 9, 15), datetime.date(2017, 9, 18), 1026, 707, 36, Decimal('160.05'), 6),
 (89, datetime.date(2017, 9, 15), datetime.date(2017, 9, 18), 1003, 703, 15, Decimal('4.84'), 6),
 (90, datetime.date(2017, 9, 15), datetime.date(2017, 9, 16), 1017, 706, 33, Decimal('19.00'), 3),
 (91, datetime.date(2017, 9, 15), datetime.date(2017, 9, 19), 1010, 703, 1, Decimal('1164.00'), 5),
 (92, datetime.date(2017, 9, 15), datetime.date(2017, 9, 18), 1011, 704, 1, Decimal('1200.00'), 3),
 (93, datetime.date(2017, 9, 15), datetime.date(2017, 9, 18), 1023, 707, 3, Decimal('75.00'), 1),
 (94, datetime.date(2017, 9, 15), datetime.date(2017, 9, 15), 1010, 701, 1, Decimal('1200.00'), 2),
 (95, datetime.date(2017, 9, 16), datetime.date(2017, 9, 20), 1021, 704, 5, Decimal('7.23'), 5),
 (96, datetime.date(2017, 9, 16), datetime.date(2017, 9, 17), 1025, 703, 1, Decimal('1200.00'), 4),
 (97, datetime.date(2017, 9, 16), datetime.date(2017, 9, 19), 1026, 703, 1, Decimal('1200.00'), 2),
 (98, datetime.date(2017, 9, 16), datetime.date(2017, 9, 17), 1009, 706, 1, Decimal('1200.00'), 4),
 (99, datetime.date(2017, 9, 16), datetime.date(2017, 9, 19), 1002, 703, 1, Decimal('1200.00'), 4),
 (100, datetime.date(2017, 9, 16), datetime.date(2017, 9, 17), 1002, 707, 3, Decimal('75.00'), 3),
 (101, datetime.date(2017, 9, 16), datetime.date(2017, 9, 19), 1023, 707, 7, Decimal('47.53'), 6),
 (102, datetime.date(2017, 9, 16), datetime.date(2017, 9, 18), 1010, 705, 1, Decimal('1200.00'), 3),
 (103, datetime.date(2017, 9, 16), datetime.date(2017, 9, 17), 1025, 702, 1, Decimal('1164.00'), 5),
 (104, datetime.date(2017, 9, 16), datetime.date(2017, 9, 16), 1017, 708, 1, Decimal('1200.00'), 3),
 (105, datetime.date(2017, 9, 17), datetime.date(2017, 9, 19), 1005, 704, 2, Decimal('1746.00'), 5),
 (106, datetime.date(2017, 9, 17), datetime.date(2017, 9, 21), 1020, 708, 32, Decimal('32.00'), 4),
 (107, datetime.date(2017, 9, 17), datetime.date(2017, 9, 21), 1001, 703, 17, Decimal('45.00'), 2),
 (108, datetime.date(2017, 9, 17), datetime.date(2017, 9, 20), 1004, 701, 31, Decimal('22.00'), 4),
 (109, datetime.date(2017, 9, 17), datetime.date(2017, 9, 17), 1013, 703, 39, Decimal('175.00'), 4),
 (110, datetime.date(2017, 9, 18), datetime.date(2017, 9, 20), 1015, 708, 16, Decimal('27.16'), 6),
 (111, datetime.date(2017, 9, 18), datetime.date(2017, 9, 22), 1021, 707, 2, Decimal('1746.00'), 6),
 (112, datetime.date(2017, 9, 19), datetime.date(2017, 9, 20), 1009, 703, 16, Decimal('28.00'), 3),
 (113, datetime.date(2017, 9, 19), datetime.date(2017, 9, 23), 1010, 702, 1, Decimal('1200.00'), 4),
 (114, datetime.date(2017, 9, 19), datetime.date(2017, 9, 23), 1011, 706, 17, Decimal('43.65'), 5),
 (115, datetime.date(2017, 9, 20), datetime.date(2017, 9, 22), 1003, 704, 8, Decimal('50.00'), 4),
 (116, datetime.date(2017, 9, 20), datetime.date(2017, 9, 22), 1004, 701, 1, Decimal('1200.00'), 3),
 (117, datetime.date(2017, 9, 21), datetime.date(2017, 9, 23), 1005, 705, 1, Decimal('1164.00'), 6),
 (118, datetime.date(2017, 9, 21), datetime.date(2017, 9, 23), 1021, 708, 33, Decimal('18.43'), 6),
 (119, datetime.date(2017, 9, 21), datetime.date(2017, 9, 21), 1013, 701, 1, Decimal('1164.00'), 6),
 (120, datetime.date(2017, 9, 21), datetime.date(2017, 9, 22), 1024, 702, 1, Decimal('1200.00'), 2),
 (121, datetime.date(2017, 9, 21), datetime.date(2017, 9, 22), 1025, 701, 1, Decimal('1200.00'), 2),
 (122, datetime.date(2017, 9, 21), datetime.date(2017, 9, 25), 1009, 707, 1, Decimal('1200.00'), 3),
 (123, datetime.date(2017, 9, 21), datetime.date(2017, 9, 23), 1004, 704, 6, Decimal('615.95'), 5),
 (124, datetime.date(2017, 9, 22), datetime.date(2017, 9, 24), 1007, 705, 1, Decimal('1164.00'), 6),
 (125, datetime.date(2017, 9, 22), datetime.date(2017, 9, 22), 1011, 707, 1, Decimal('1200.00'), 3),
 (126, datetime.date(2017, 9, 23), datetime.date(2017, 9, 25), 1016, 708, 9, Decimal('32.01'), 6),
 (127, datetime.date(2017, 9, 23), datetime.date(2017, 9, 26), 1009, 705, 1, Decimal('1164.00'), 6),
 (128, datetime.date(2017, 9, 23), datetime.date(2017, 9, 27), 1022, 708, 21, Decimal('53.35'), 5),
 (129, datetime.date(2017, 9, 23), datetime.date(2017, 9, 23), 1007, 708, 24, Decimal('69.00'), 1),
 (130, datetime.date(2017, 9, 23), datetime.date(2017, 9, 25), 1011, 705, 1, Decimal('1164.00'), 5),
 (131, datetime.date(2017, 9, 23), datetime.date(2017, 9, 23), 1014, 706, 1, Decimal('1164.00'), 6),
 (132, datetime.date(2017, 9, 23), datetime.date(2017, 9, 26), 1007, 705, 1, Decimal('1200.00'), 2),
 (133, datetime.date(2017, 9, 23), datetime.date(2017, 9, 23), 1027, 706, 9, Decimal('33.00'), 2),
 (134, datetime.date(2017, 9, 23), datetime.date(2017, 9, 25), 1003, 703, 16, Decimal('28.00'), 2),
 (135, datetime.date(2017, 9, 24), datetime.date(2017, 9, 27), 1005, 701, 6, Decimal('615.95'), 5),
 (136, datetime.date(2017, 9, 24), datetime.date(2017, 9, 27), 1008, 707, 1, Decimal('1200.00'), 3),
 (137, datetime.date(2017, 9, 24), datetime.date(2017, 9, 24), 1001, 706, 16, Decimal('28.00'), 3),
 (138, datetime.date(2017, 9, 25), datetime.date(2017, 9, 28), 1001, 702, 10, Decimal('36.00'), 4),
 (139, datetime.date(2017, 9, 25), datetime.date(2017, 9, 27), 1024, 704, 32, Decimal('32.00'), 4),
 (140, datetime.date(2017, 9, 25), datetime.date(2017, 9, 25), 1002, 706, 1, Decimal('1200.00'), 3),
 (141, datetime.date(2017, 9, 25), datetime.date(2017, 9, 28), 1014, 706, 1, Decimal('1200.00'), 2),
 (142, datetime.date(2017, 9, 26), datetime.date(2017, 9, 30), 1018, 702, 1, Decimal('1200.00'), 3),
 (143, datetime.date(2017, 9, 26), datetime.date(2017, 9, 29), 1021, 706, 17, Decimal('45.00'), 2),
 (144, datetime.date(2017, 9, 26), datetime.date(2017, 9, 30), 1018, 704, 1, Decimal('1164.00'), 6),
 (145, datetime.date(2017, 9, 27), datetime.date(2017, 10, 1), 1027, 701, 1, Decimal('1200.00'), 3),
 (146, datetime.date(2017, 9, 27), datetime.date(2017, 9, 27), 1021, 708, 18, Decimal('179.00'), 2),
 (147, datetime.date(2017, 9, 27), datetime.date(2017, 9, 27), 1026, 708, 1, Decimal('1200.00'), 2),
 (148, datetime.date(2017, 9, 27), datetime.date(2017, 10, 1), 1027, 704, 1, Decimal('1200.00'), 1),
 (149, datetime.date(2017, 9, 28), datetime.date(2017, 9, 29), 1004, 707, 1, Decimal('1200.00'), 4),
 (150, datetime.date(2017, 9, 28), datetime.date(2017, 9, 28), 1024, 701, 1, Decimal('1164.00'), 6),
 (151, datetime.date(2017, 9, 28), datetime.date(2017, 9, 29), 1001, 707, 24, Decimal('69.00'), 4),
 (152, datetime.date(2017, 9, 29), datetime.date(2017, 10, 3), 1017, 704, 2, Decimal('1800.00'), 3),
 (153, datetime.date(2017, 9, 30), datetime.date(2017, 10, 1), 1003, 702, 7, Decimal('49.00'), 1),
 (154, datetime.date(2017, 9, 30), datetime.date(2017, 10, 3), 1001, 703, 14, Decimal('139.95'), 4),
 (155, datetime.date(2017, 9, 30), datetime.date(2017, 10, 4), 1004, 703, 10, Decimal('36.00'), 4),
 (156, datetime.date(2017, 9, 30), datetime.date(2017, 10, 1), 1004, 703, 1, Decimal('1164.00'), 6),
 (157, datetime.date(2017, 9, 30), datetime.date(2017, 10, 2), 1010, 707, 1, Decimal('1164.00'), 6),
 (158, datetime.date(2017, 9, 30), datetime.date(2017, 10, 4), 1021, 705, 21, Decimal('53.35'), 6),
 (159, datetime.date(2017, 9, 30), datetime.date(2017, 10, 4), 1005, 707, 10, Decimal('34.92'), 5),
 (160, datetime.date(2017, 10, 1), datetime.date(2017, 10, 1), 1021, 706, 1, Decimal('1200.00'), 1),
 (161, datetime.date(2017, 10, 1), datetime.date(2017, 10, 1), 1011, 707, 1, Decimal('1200.00'), 2),
 (162, datetime.date(2017, 10, 1), datetime.date(2017, 10, 2), 1021, 704, 11, Decimal('1600.50'), 5),
 (163, datetime.date(2017, 10, 1), datetime.date(2017, 10, 1), 1004, 707, 1, Decimal('1164.00'), 6),
 (164, datetime.date(2017, 10, 2), datetime.date(2017, 10, 5), 1021, 707, 1, Decimal('1164.00'), 6),
 (165, datetime.date(2017, 10, 3), datetime.date(2017, 10, 3), 1017, 702, 1, Decimal('1164.00'), 6),
 (166, datetime.date(2017, 10, 4), datetime.date(2017, 10, 7), 1022, 706, 7, Decimal('49.00'), 3),
 (167, datetime.date(2017, 10, 4), datetime.date(2017, 10, 4), 1017, 706, 1, Decimal('1164.00'), 5),
 (168, datetime.date(2017, 10, 4), datetime.date(2017, 10, 6), 1027, 706, 1, Decimal('1200.00'), 1),
 (169, datetime.date(2017, 10, 4), datetime.date(2017, 10, 7), 1025, 708, 9, Decimal('33.00'), 1),
 (170, datetime.date(2017, 10, 5), datetime.date(2017, 10, 5), 1004, 704, 1, Decimal('1200.00'), 3),
 (171, datetime.date(2017, 10, 5), datetime.date(2017, 10, 6), 1026, 707, 38, Decimal('166.00'), 4),
 (172, datetime.date(2017, 10, 5), datetime.date(2017, 10, 8), 1018, 704, 1, Decimal('1200.00'), 2),
 (173, datetime.date(2017, 10, 5), datetime.date(2017, 10, 5), 1015, 704, 22, Decimal('82.00'), 3),
 (174, datetime.date(2017, 10, 5), datetime.date(2017, 10, 9), 1006, 703, 1, Decimal('1164.00'), 6),
 (175, datetime.date(2017, 10, 5), datetime.date(2017, 10, 8), 1013, 706, 1, Decimal('1164.00'), 5),
 (176, datetime.date(2017, 10, 5), datetime.date(2017, 10, 5), 1025, 701, 7, Decimal('47.53'), 5),
 (177, datetime.date(2017, 10, 5), datetime.date(2017, 10, 9), 1008, 706, 1, Decimal('1200.00'), 4),
 (178, datetime.date(2017, 10, 5), datetime.date(2017, 10, 8), 1022, 702, 16, Decimal('28.00'), 1),
 (179, datetime.date(2017, 10, 5), datetime.date(2017, 10, 9), 1017, 708, 1, Decimal('1164.00'), 5),
 (180, datetime.date(2017, 10, 6), datetime.date(2017, 10, 9), 1015, 708, 21, Decimal('55.00'), 4),
 (181, datetime.date(2017, 10, 6), datetime.date(2017, 10, 6), 1017, 708, 1, Decimal('1200.00'), 3),
 (182, datetime.date(2017, 10, 6), datetime.date(2017, 10, 7), 1002, 702, 1, Decimal('1164.00'), 6),
 (183, datetime.date(2017, 10, 6), datetime.date(2017, 10, 6), 1020, 708, 1, Decimal('1200.00'), 2),
 (184, datetime.date(2017, 10, 6), datetime.date(2017, 10, 10), 1023, 707, 1, Decimal('1200.00'), 3),
 (185, datetime.date(2017, 10, 6), datetime.date(2017, 10, 10), 1017, 702, 1, Decimal('1200.00'), 4),
 (186, datetime.date(2017, 10, 6), datetime.date(2017, 10, 6), 1002, 704, 5, Decimal('7.23'), 6),
 (187, datetime.date(2017, 10, 7), datetime.date(2017, 10, 8), 1022, 702, 22, Decimal('79.54'), 5),
 (188, datetime.date(2017, 10, 7), datetime.date(2017, 10, 8), 1002, 706, 1, Decimal('1164.00'), 6),
 (189, datetime.date(2017, 10, 7), datetime.date(2017, 10, 8), 1012, 702, 5, Decimal('7.23'), 5),
 (190, datetime.date(2017, 10, 7), datetime.date(2017, 10, 11), 1024, 708, 29, Decimal('32.98'), 6),
 (191, datetime.date(2017, 10, 7), datetime.date(2017, 10, 8), 1015, 701, 8, Decimal('48.50'), 5),
 (192, datetime.date(2017, 10, 7), datetime.date(2017, 10, 10), 1022, 702, 17, Decimal('43.65'), 6),
 (193, datetime.date(2017, 10, 7), datetime.date(2017, 10, 7), 1025, 708, 1, Decimal('1200.00'), 2),
 (194, datetime.date(2017, 10, 7), datetime.date(2017, 10, 9), 1017, 708, 1, Decimal('1200.00'), 3),
 (195, datetime.date(2017, 10, 8), datetime.date(2017, 10, 11), 1025, 703, 39, Decimal('175.00'), 4),
 (196, datetime.date(2017, 10, 8), datetime.date(2017, 10, 12), 1009, 707, 1, Decimal('1200.00'), 1),
 (197, datetime.date(2017, 10, 8), datetime.date(2017, 10, 11), 1002, 703, 18, Decimal('179.00'), 1),
 (198, datetime.date(2017, 10, 8), datetime.date(2017, 10, 10), 1002, 703, None, None, None),
 (199, datetime.date(2017, 10, 8), datetime.date(2017, 10, 10), 1008, 707, 9, Decimal('33.00'), 4),
 (200, datetime.date(2017, 10, 8), datetime.date(2017, 10, 9), 1026, 706, 1, Decimal('1164.00'), 5),
 (201, datetime.date(2017, 10, 8), datetime.date(2017, 10, 9), 1018, 701, 5, Decimal('7.23'), 6),

In [16]:
%%sql

-- bad because mixes aggregated and random 

SELECT orders.*, COUNT(ProductNumber) as nitems FROM orders  NATURAL LEFT JOIN order_details
GROUP BY OrderNumber
HAVING nitems = 0

 * mysql://dimitri:***@db.data-science-ust.net
11 rows affected.

[(198, datetime.date(2017, 10, 8), datetime.date(2017, 10, 10), 1002, 703, 0),
 (216, datetime.date(2017, 10, 12), datetime.date(2017, 10, 12), 1016, 707, 0),
 (305, datetime.date(2017, 11, 1), datetime.date(2017, 11, 5), 1013, 708, 0),
 (361, datetime.date(2017, 11, 12), datetime.date(2017, 11, 13), 1016, 706, 0),
 (484, datetime.date(2017, 12, 9), datetime.date(2017, 12, 10), 1021, 707, 0),
 (523, datetime.date(2017, 12, 15), datetime.date(2017, 12, 17), 1003, 704, 0),
 (629, datetime.date(2018, 1, 8), datetime.date(2018, 1, 12), 1014, 704, 0),
 (632, datetime.date(2018, 1, 8), datetime.date(2018, 1, 12), 1001, 706, 0),
 (689, datetime.date(2018, 1, 15), datetime.date(2018, 1, 16), 1015, 705, 0),
 (753, datetime.date(2018, 1, 28), datetime.date(2018, 1, 30), 1013, 701, 0),
 (816, datetime.date(2018, 2, 9), datetime.date(2018, 2, 12), 1011, 701, 0)]

In [17]:
%%sql

SELECT orders.*, ProductNumber as nitems FROM orders  NATURAL LEFT JOIN order_details

 * mysql://dimitri:***@db.data-science-ust.net
3984 rows affected.

[(1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 1),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 6),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 11),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 16),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 21),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 26),
 (1, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1018, 707, 40),
 (2, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1001, 703, 27),
 (2, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1001, 703, 40),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 1),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 6),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 11),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 16),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 21),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 26),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 31),
 (3, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1002, 707, 36),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 1),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 9),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 17),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 25),
 (4, datetime.date(2017, 9, 2), datetime.date(2017, 9, 4), 1009, 703, 39),
 (5, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1024, 708, 1),
 (5, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1024, 708, 14),
 (5, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1024, 708, 31),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 2),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 7),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 12),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 17),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 22),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 27),
 (6, datetime.date(2017, 9, 2), datetime.date(2017, 9, 6), 1014, 702, 32),
 (7, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1001, 708, 14),
 (7, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1001, 708, 27),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 16),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 22),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 28),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 34),
 (8, datetime.date(2017, 9, 2), datetime.date(2017, 9, 2), 1003, 703, 40),
 (9, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1007, 708, 24),
 (10, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1012, 701, 1),
 (10, datetime.date(2017, 9, 2), datetime.date(2017, 9, 5), 1012, 701, 24),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 1),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 6),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 11),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 16),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 21),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 26),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 31),
 (11, datetime.date(2017, 9, 3), datetime.date(2017, 9, 5), 1020, 706, 36),
 (12, datetime.date(2017, 9, 3), datetime.date(2017, 9, 6), 1024, 706, 10),
 (13, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1024, 704, 1),
 (13, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1024, 704, 11),
 (13, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1024, 704, 28),
 (13, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1024, 704, 38),
 (14, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1013, 704, 1),
 (14, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1013, 704, 14),
 (14, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1013, 704, 40),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 1),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 9),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 17),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 29),
 (15, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1004, 701, 37),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 9),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 14),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 19),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 24),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 29),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 34),
 (16, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1001, 707, 39),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 1),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 7),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 13),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 19),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 25),
 (17, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1014, 702, 36),
 (18, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1016, 708, 12),
 (18, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1016, 708, 20),
 (18, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1016, 708, 28),
 (18, datetime.date(2017, 9, 3), datetime.date(2017, 9, 4), 1016, 708, 36),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 1),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 6),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 11),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 20),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 25),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 30),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 35),
 (19, datetime.date(2017, 9, 3), datetime.date(2017, 9, 7), 1027, 707, 40),
 (20, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1011, 706, 1),
 (20, datetime.date(2017, 9, 3), datetime.date(2017, 9, 3), 1011, 706, 37),
 (21, datetime.date(2017, 9, 4), datetime.date(2017, 9, 4), 1014, 702, 3),
 (21, datetime.date(2017, 9, 4), datetime.date(2017, 9, 4), 1014, 702, 13),
 (21, datetime.date(2017, 9, 4), datetime.date(2017, 9, 4), 1014, 702, 33),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 1),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 7),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 17),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 29),
 (22, datetime.date(2017, 9, 4), datetime.date(2017, 9, 8), 1026, 702, 35),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 1),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 6),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 11),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 16),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 21),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 29),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 34),
 (23, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 705, 39),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 9),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 14),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 19),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 24),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 29),
 (24, datetime.date(2017, 9, 4), datetime.date(2017, 9, 6), 1010, 705, 34),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 1),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 11),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 17),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 29),
 (25, datetime.date(2017, 9, 4), datetime.date(2017, 9, 5), 1017, 708, 35),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 1),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 7),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 13),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 24),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 30),
 (26, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1013, 707, 36),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 1),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 7),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 13),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 26),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 32),
 (27, datetime.date(2017, 9, 5), datetime.date(2017, 9, 6), 1014, 703, 38),
 (28, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1004, 703, 7),
 (28, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1004, 703, 27),
 (29, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1015, 707, 38),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 1),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 9),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 17),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 29),
 (30, datetime.date(2017, 9, 5), datetime.date(2017, 9, 9), 1010, 708, 37),
 (31, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1014, 701, 16),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 1),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 7),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 19),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 25),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 31),
 (32, datetime.date(2017, 9, 6), datetime.date(2017, 9, 10), 1012, 704, 37),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 1),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 7),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 13),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 19),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 33),
 (33, datetime.date(2017, 9, 6), datetime.date(2017, 9, 7), 1024, 704, 39),
 (34, datetime.date(2017, 9, 7), datetime.date(2017, 9, 8), 1010, 705, 8),
 (34, datetime.date(2017, 9, 7), datetime.date(2017, 9, 8), 1010, 705, 28),
 (35, datetime.date(2017, 9, 7), datetime.date(2017, 9, 7), 1012, 701, 1),
 (35, datetime.date(2017, 9, 7), datetime.date(2017, 9, 7), 1012, 701, 14),
 (35, datetime.date(2017, 9, 7), datetime.date(2017, 9, 7), 1012, 701, 32),
 (36, datetime.date(2017, 9, 7), datetime.date(2017, 9, 8), 1007, 705, 5),
 (37, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1027, 702, 8),
 (37, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1027, 702, 18),
 (37, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1027, 702, 28),
 (37, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1027, 702, 38),
 (38, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1017, 702, 39),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 1),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 6),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 11),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 16),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 21),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 26),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 31),
 (39, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1004, 704, 36),
 (40, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1017, 703, 6),
 (40, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1017, 703, 19),
 (40, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1017, 703, 32),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 10),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 16),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 22),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 28),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 34),
 (41, datetime.date(2017, 9, 8), datetime.date(2017, 9, 8), 1008, 706, 40),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 1),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 9),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 19),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 27),
 (42, datetime.date(2017, 9, 8), datetime.date(2017, 9, 11), 1012, 704, 35),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 1),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 6),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 11),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 16),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 28),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 33),
 (43, datetime.date(2017, 9, 8), datetime.date(2017, 9, 12), 1020, 705, 38),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 1),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 7),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 13),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 26),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 32),
 (44, datetime.date(2017, 9, 8), datetime.date(2017, 9, 9), 1005, 701, 38),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 1),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 6),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 11),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 16),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 25),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 30),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 35),
 (45, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1008, 708, 40),
 (46, datetime.date(2017, 9, 9), datetime.date(2017, 9, 10), 1018, 707, 35),
 (47, datetime.date(2017, 9, 9), datetime.date(2017, 9, 11), 1023, 708, 1),
 (48, datetime.date(2017, 9, 9), datetime.date(2017, 9, 12), 1004, 707, 1),
 (48, datetime.date(2017, 9, 9), datetime.date(2017, 9, 12), 1004, 707, 20),
 (48, datetime.date(2017, 9, 9), datetime.date(2017, 9, 12), 1004, 707, 33),
 (49, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1015, 704, 13),
 (49, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1015, 704, 19),
 (49, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1015, 704, 25),
 (49, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1015, 704, 31),
 (49, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1015, 704, 37),
 (50, datetime.date(2017, 9, 9), datetime.date(2017, 9, 13), 1002, 704, 5),
 (50, datetime.date(2017, 9, 9), datetime.date(2017, 9, 13), 1002, 704, 15),
 (50, datetime.date(2017, 9, 9), datetime.date(2017, 9, 13), 1002, 704, 25),
 (50, datetime.date(2017, 9, 9), datetime.date(2017, 9, 13), 1002, 704, 35),
 (51, datetime.date(2017, 9, 9), datetime.date(2017, 9, 9), 1018, 707, 1),
 (52, datetime.date(2017, 9, 10), datetime.date(2017, 9, 12), 1001, 701, 30),
 (53, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 706, 1),
 (53, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 706, 6),
 (53, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 706, 11),
 (53, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 706, 16),
 (53, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 706, 21),
 (53, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 706, 34),
 (53, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 706, 39),
 (54, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1007, 707, 10),
 (55, datetime.date(2017, 9, 10), datetime.date(2017, 9, 12), 1001, 707, 10),
 (56, datetime.date(2017, 9, 10), datetime.date(2017, 9, 13), 1014, 702, 6),
 (56, datetime.date(2017, 9, 10), datetime.date(2017, 9, 13), 1014, 702, 16),
 (56, datetime.date(2017, 9, 10), datetime.date(2017, 9, 13), 1014, 702, 26),
 (56, datetime.date(2017, 9, 10), datetime.date(2017, 9, 13), 1014, 702, 36),
 (57, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 703, 1),
 (57, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 703, 14),
 (57, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 703, 20),
 (57, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 703, 26),
 (57, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 703, 32),
 (57, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 703, 38),
 (58, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1006, 701, 1),
 (58, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1006, 701, 7),
 (58, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1006, 701, 13),
 (58, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1006, 701, 19),
 (58, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1006, 701, 31),
 (58, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1006, 701, 37),
 (59, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 704, 1),
 (59, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 704, 6),
 (59, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 704, 11),
 (59, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 704, 21),
 (59, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 704, 26),
 (59, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 704, 31),
 (59, datetime.date(2017, 9, 10), datetime.date(2017, 9, 10), 1004, 704, 36),
 (60, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1013, 708, 1),
 (60, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1013, 708, 6),
 (60, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1013, 708, 11),
 (60, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1013, 708, 16),
 (60, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1013, 708, 28),
 (60, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1013, 708, 33),
 (60, datetime.date(2017, 9, 10), datetime.date(2017, 9, 14), 1013, 708, 38),
 (61, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 706, 1),
 (61, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 706, 9),
 (61, datetime.date(2017, 9, 10), datetime.date(2017, 9, 11), 1009, 706, 17),

## Example problems

In [18]:
%%sql

-- Customers and the number of orders that they made

SELECT CustomerID, CustFirstName, CustLastName, count(OrderNumber) as norders
FROM customers  NATURAL LEFT JOIN orders
GROUP BY CustomerID
ORDER BY norders

 * mysql://dimitri:***@db.data-science-ust.net
28 rows affected.

[(1028, 'Jeffrey', 'Tirekicker', 0),
 (1022, 'Caleb', 'Viescas', 20),
 (1019, 'Zachary', 'Ehrlich', 23),
 (1023, 'Julia', 'Schnebly', 25),
 (1018, 'David', 'Smith', 26),
 (1006, 'John', 'Viescas', 27),
 (1015, 'Darren', 'Gehring', 29),
 (1008, 'Neil', 'Patterson', 31),
 (1010, 'Angel', 'Kennedy', 32),
 (1027, 'Luke', 'Patterson', 33),
 (1011, 'Alaina', 'Hallmark', 33),
 (1003, 'Gary', 'Hallmark', 35),
 (1026, 'Kirk', 'DeGrasse', 35),
 (1013, 'Rachel', 'Patterson', 36),
 (1007, 'Mariya', 'Sergienko', 36),
 (1009, 'Andrew', 'Cencini', 37),
 (1020, 'Joyce', 'Bonnicksen', 37),
 (1016, 'Jim', 'Wilson', 38),
 (1004, 'Robert', 'Brown', 39),
 (1012, 'Liz', 'Keyser', 39),
 (1005, 'Dean', 'McCrae', 40),
 (1002, 'William', 'Thompson', 40),
 (1024, 'Mark', 'Rosales', 41),
 (1014, 'Sam', 'Abolrous', 41),
 (1025, 'Maria', 'Patterson', 41),
 (1021, 'Estella', 'Pundt', 42),
 (1001, 'Suzanne', 'Viescas', 44),
 (1017, 'Manuela', 'Seidel', 44)]

In [19]:
%%sql

-- orders with their total amounts


SELECT OrderNumber, OrderDate, IFNULL(sum(QuotedPrice * QuantityOrdered), 0) as total_amount
FROM orders NATURAL LEFT JOIN order_details 
GROUP BY OrderNumber
ORDER BY total_amount

 * mysql://dimitri:***@db.data-science-ust.net
944 rows affected.

[(816, datetime.date(2018, 2, 9), Decimal('0.00')),
 (216, datetime.date(2017, 10, 12), Decimal('0.00')),
 (632, datetime.date(2018, 1, 8), Decimal('0.00')),
 (305, datetime.date(2017, 11, 1), Decimal('0.00')),
 (361, datetime.date(2017, 11, 12), Decimal('0.00')),
 (689, datetime.date(2018, 1, 15), Decimal('0.00')),
 (753, datetime.date(2018, 1, 28), Decimal('0.00')),
 (523, datetime.date(2017, 12, 15), Decimal('0.00')),
 (484, datetime.date(2017, 12, 9), Decimal('0.00')),
 (629, datetime.date(2018, 1, 8), Decimal('0.00')),
 (198, datetime.date(2017, 10, 8), Decimal('0.00')),
 (522, datetime.date(2017, 12, 14), Decimal('4.99')),
 (36, datetime.date(2017, 9, 7), Decimal('7.45')),
 (275, datetime.date(2017, 10, 25), Decimal('14.90')),
 (930, datetime.date(2018, 2, 28), Decimal('15.00')),
 (915, datetime.date(2018, 2, 25), Decimal('28.00')),
 (255, datetime.date(2017, 10, 22), Decimal('28.00')),
 (814, datetime.date(2018, 2, 9), Decimal('33.00')),
 (55, datetime.date(2017, 9, 10), Decimal('36.00')),
 (920, datetime.date(2018, 2, 27), Decimal('36.15')),
 (424, datetime.date(2017, 11, 26), Decimal('39.00')),
 (201, datetime.date(2017, 10, 8), Decimal('43.38')),
 (228, datetime.date(2017, 10, 16), Decimal('45.00')),
 (435, datetime.date(2017, 11, 28), Decimal('47.00')),
 (527, datetime.date(2017, 12, 16), Decimal('49.00')),
 (324, datetime.date(2017, 11, 3), Decimal('50.00')),
 (914, datetime.date(2018, 2, 25), Decimal('55.00')),
 (576, datetime.date(2017, 12, 28), Decimal('56.00')),
 (90, datetime.date(2017, 9, 15), Decimal('57.00')),
 (133, datetime.date(2017, 9, 23), Decimal('66.00')),
 (802, datetime.date(2018, 2, 5), Decimal('67.00')),
 (823, datetime.date(2018, 2, 10), Decimal('68.00')),
 (9, datetime.date(2017, 9, 2), Decimal('69.00')),
 (129, datetime.date(2017, 9, 23), Decimal('69.00')),
 (12, datetime.date(2017, 9, 3), Decimal('72.00')),
 (54, datetime.date(2017, 9, 10), Decimal('72.00')),
 (93, datetime.date(2017, 9, 15), Decimal('75.00')),
 (46, datetime.date(2017, 9, 9), Decimal('78.00')),
 (341, datetime.date(2017, 11, 7), Decimal('81.00')),
 (446, datetime.date(2017, 11, 30), Decimal('87.98')),
 (108, datetime.date(2017, 9, 17), Decimal('88.00')),
 (430, datetime.date(2017, 11, 27), Decimal('102.00')),
 (369, datetime.date(2017, 11, 13), Decimal('108.00')),
 (494, datetime.date(2017, 12, 10), Decimal('108.00')),
 (613, datetime.date(2018, 1, 4), Decimal('110.00')),
 (118, datetime.date(2017, 9, 21), Decimal('110.58')),
 (855, datetime.date(2018, 2, 15), Decimal('117.00')),
 (106, datetime.date(2017, 9, 17), Decimal('128.00')),
 (139, datetime.date(2017, 9, 25), Decimal('128.00')),
 (471, datetime.date(2017, 12, 6), Decimal('130.95')),
 (394, datetime.date(2017, 11, 19), Decimal('130.97')),
 (648, datetime.date(2018, 1, 10), Decimal('132.00')),
 (768, datetime.date(2018, 1, 31), Decimal('135.00')),
 (621, datetime.date(2018, 1, 6), Decimal('135.00')),
 (889, datetime.date(2018, 2, 21), Decimal('136.00')),
 (524, datetime.date(2017, 12, 16), Decimal('136.00')),
 (601, datetime.date(2018, 1, 2), Decimal('136.80')),
 (877, datetime.date(2018, 2, 19), Decimal('138.00')),
 (857, datetime.date(2018, 2, 15), Decimal('139.00')),
 (549, datetime.date(2017, 12, 22), Decimal('140.65')),
 (770, datetime.date(2018, 1, 31), Decimal('144.00')),
 (562, datetime.date(2017, 12, 25), Decimal('147.00')),
 (212, datetime.date(2017, 10, 11), Decimal('150.00')),
 (892, datetime.date(2018, 2, 22), Decimal('156.00')),
 (574, datetime.date(2017, 12, 27), Decimal('160.05')),
 (647, datetime.date(2018, 1, 10), Decimal('161.50')),
 (262, datetime.date(2017, 10, 23), Decimal('162.96')),
 (31, datetime.date(2017, 9, 6), Decimal('162.96')),
 (417, datetime.date(2017, 11, 25), Decimal('166.00')),
 (758, datetime.date(2018, 1, 29), Decimal('168.78')),
 (488, datetime.date(2017, 12, 9), Decimal('171.00')),
 (885, datetime.date(2018, 2, 21), Decimal('173.00')),
 (832, datetime.date(2018, 2, 12), Decimal('175.00')),
 (197, datetime.date(2017, 10, 8), Decimal('179.00')),
 (143, datetime.date(2017, 9, 26), Decimal('180.00')),
 (436, datetime.date(2017, 11, 28), Decimal('180.20')),
 (407, datetime.date(2017, 11, 23), Decimal('188.68')),
 (504, datetime.date(2017, 12, 12), Decimal('189.00')),
 (518, datetime.date(2017, 12, 14), Decimal('194.05')),
 (568, datetime.date(2017, 12, 26), Decimal('197.88')),
 (190, datetime.date(2017, 10, 7), Decimal('197.88')),
 (287, datetime.date(2017, 10, 27), Decimal('197.90')),
 (749, datetime.date(2018, 1, 26), Decimal('200.00')),
 (482, datetime.date(2017, 12, 8), Decimal('207.00')),
 (380, datetime.date(2017, 11, 14), Decimal('207.00')),
 (564, datetime.date(2017, 12, 25), Decimal('214.00')),
 (320, datetime.date(2017, 11, 3), Decimal('220.00')),
 (728, datetime.date(2018, 1, 23), Decimal('220.00')),
 (451, datetime.date(2017, 12, 1), Decimal('220.00')),
 (931, datetime.date(2018, 2, 28), Decimal('225.00')),
 (619, datetime.date(2018, 1, 6), Decimal('225.00')),
 (526, datetime.date(2017, 12, 16), Decimal('228.05')),
 (326, datetime.date(2017, 11, 3), Decimal('242.50')),
 (462, datetime.date(2017, 12, 4), Decimal('254.25')),
 (623, datetime.date(2018, 1, 7), Decimal('259.50')),
 (408, datetime.date(2017, 11, 24), Decimal('261.90')),
 (737, datetime.date(2018, 1, 25), Decimal('261.90')),
 (52, datetime.date(2017, 9, 10), Decimal('261.90')),
 (587, datetime.date(2017, 12, 30), Decimal('264.00')),
 (264, datetime.date(2017, 10, 23), Decimal('266.75')),
 (365, datetime.date(2017, 11, 12), Decimal('267.30')),
 (593, datetime.date(2017, 12, 31), Decimal('270.00')),
 (595, datetime.date(2018, 1, 1), Decimal('273.54')),
 (68, datetime.date(2017, 9, 12), Decimal('273.54')),
 (664, datetime.date(2018, 1, 12), Decimal('276.00')),
 (151, datetime.date(2017, 9, 28), Decimal('276.00')),
 (425, datetime.date(2017, 11, 27), Decimal('286.00')),
 (209, datetime.date(2017, 10, 11), Decimal('289.00')),
 (512, datetime.date(2017, 12, 13), Decimal('291.00')),
 (692, datetime.date(2018, 1, 16), Decimal('296.90')),
 (448, datetime.date(2017, 11, 30), Decimal('301.90')),
 (158, datetime.date(2017, 9, 30), Decimal('320.10')),
 (186, datetime.date(2017, 10, 6), Decimal('321.38')),
 (890, datetime.date(2018, 2, 21), Decimal('332.00')),
 (277, datetime.date(2017, 10, 25), Decimal('333.80')),
 (204, datetime.date(2017, 10, 9), Decimal('334.65')),
 (543, datetime.date(2017, 12, 22), Decimal('334.65')),
 (28, datetime.date(2017, 9, 5), Decimal('335.68')),
 (645, datetime.date(2018, 1, 9), Decimal('339.60')),
 (638, datetime.date(2018, 1, 8), Decimal('340.65')),
 (114, datetime.date(2017, 9, 19), Decimal('353.25')),
 (146, datetime.date(2017, 9, 27), Decimal('358.00')),
 (653, datetime.date(2018, 1, 11), Decimal('373.45')),
 (456, datetime.date(2017, 12, 2), Decimal('375.00')),
 (683, datetime.date(2018, 1, 14), Decimal('375.00')),
 (128, datetime.date(2017, 9, 23), Decimal('377.33')),
 (288, datetime.date(2017, 10, 27), Decimal('383.15')),
 (820, datetime.date(2018, 2, 9), Decimal('401.58')),
 (773, datetime.date(2018, 1, 31), Decimal('401.58')),
 (234, datetime.date(2017, 10, 17), Decimal('402.00')),
 (413, datetime.date(2017, 11, 25), Decimal('402.00')),
 (299, datetime.date(2017, 10, 31), Decimal('402.95')),
 (764, datetime.date(2018, 1, 30), Decimal('403.35')),
 (546, datetime.date(2017, 12, 22), Decimal('407.25')),
 (810, datetime.date(2018, 2, 8), Decimal('409.97')),
 (34, datetime.date(2017, 9, 7), Decimal('411.28')),
 (112, datetime.date(2017, 9, 19), Decimal('414.00')),
 (519, datetime.date(2017, 12, 14), Decimal('424.33')),
 (644, datetime.date(2018, 1, 9), Decimal('431.88')),
 (314, datetime.date(2017, 11, 2), Decimal('432.75')),
 (421, datetime.date(2017, 11, 26), Decimal('441.75')),
 (759, datetime.date(2018, 1, 29), Decimal('467.14')),
 (7, datetime.date(2017, 9, 2), Decimal('467.85')),
 (173, datetime.date(2017, 10, 5), Decimal('472.98')),
 (463, datetime.date(2017, 12, 5), Decimal('477.24')),
 (50, datetime.date(2017, 9, 9), Decimal('477.94')),
 (213, datetime.date(2017, 10, 12), Decimal('492.96')),
 (396, datetime.date(2017, 11, 20), Decimal('495.78')),
 (754, datetime.date(2018, 1, 28), Decimal('498.00')),
 (397, datetime.date(2017, 11, 20), Decimal('500.00')),
 (699, datetime.date(2018, 1, 18), Decimal('503.95')),
 (226, datetime.date(2017, 10, 14), Decimal('510.00')),
 (352, datetime.date(2017, 11, 10), Decimal('523.05')),
 (202, datetime.date(2017, 10, 8), Decimal('525.00')),
 (274, datetime.date(2017, 10, 25), Decimal('537.00')),
 (624, datetime.date(2018, 1, 7), Decimal('538.00')),
 (808, datetime.date(2018, 2, 7), Decimal('544.00')),
 (501, datetime.date(2017, 12, 12), Decimal('548.95')),
 (893, datetime.date(2018, 2, 22), Decimal('550.15')),
 (875, datetime.date(2018, 2, 19), Decimal('551.00')),
 (707, datetime.date(2018, 1, 18), Decimal('556.00')),
 (382, datetime.date(2017, 11, 16), Decimal('559.80')),
 (525, datetime.date(2017, 12, 16), Decimal('560.04')),
 (429, datetime.date(2017, 11, 27), Decimal('567.00')),
 (703, datetime.date(2018, 1, 18), Decimal('570.00')),
 (534, datetime.date(2017, 12, 18), Decimal('570.90')),
 (364, datetime.date(2017, 11, 12), Decimal('571.00')),
 (798, datetime.date(2018, 2, 4), Decimal('576.55')),
 (860, datetime.date(2018, 2, 17), Decimal('585.65')),
 (70, datetime.date(2017, 9, 13), Decimal('595.20')),
 (739, datetime.date(2018, 1, 25), Decimal('606.25')),
 (656, datetime.date(2018, 1, 11), Decimal('609.65')),
 (907, datetime.date(2018, 2, 24), Decimal('615.24')),
 (793, datetime.date(2018, 2, 3), Decimal('619.70')),
 (187, datetime.date(2017, 10, 7), Decimal('624.68')),
 (608, datetime.date(2018, 1, 3), Decimal('633.05')),
 (481, datetime.date(2017, 12, 8), Decimal('637.96')),
 (83, datetime.date(2017, 9, 14), Decimal('639.00')),
 (110, datetime.date(2017, 9, 18), Decimal('641.96')),
 (89, datetime.date(2017, 9, 15), Decimal('642.04')),
 (207, datetime.date(2017, 10, 9), Decimal('647.80')),
 (705, datetime.date(2018, 1, 18), Decimal('650.10')),
 (458, datetime.date(2017, 12, 3), Decimal('654.95')),
 (235, datetime.date(2017, 10, 17), Decimal('657.00')),
 (322, datetime.date(2017, 11, 3), Decimal('660.00')),
 (918, datetime.date(2018, 2, 26), Decimal('660.00')),
 (442, datetime.date(2017, 11, 29), Decimal('662.00')),
 (171, datetime.date(2017, 10, 5), Decimal('664.00')),
 (29, datetime.date(2017, 9, 5), Decimal('664.00')),
 (646, datetime.date(2018, 1, 9), Decimal('664.00')),
 (866, datetime.date(2018, 2, 17), Decimal('674.15')),
 (577, datetime.date(2017, 12, 28), Decimal('678.25')),
 (649, datetime.date(2018, 1, 10), Decimal('686.76')),
 (195, datetime.date(2017, 10, 8), Decimal('700.00')),
 (109, datetime.date(2017, 9, 17), Decimal('700.00')),
 (38, datetime.date(2017, 9, 8), Decimal('700.00')),
 (911, datetime.date(2018, 2, 25), Decimal('705.75')),
 (470, datetime.date(2017, 12, 6), Decimal('709.32')),
 (21, datetime.date(2017, 9, 4), Decimal('709.97')),
 (489, datetime.date(2017, 12, 9), Decimal('710.30')),
 (845, datetime.date(2018, 2, 13), Decimal('716.00')),
 (349, datetime.date(2017, 11, 9), Decimal('725.80')),
 (898, datetime.date(2018, 2, 22), Decimal('727.50')),
 (230, datetime.date(2017, 10, 16), Decimal('727.50')),
 (570, datetime.date(2017, 12, 26), Decimal('742.19')),
 (180, datetime.date(2017, 10, 6), Decimal('760.00')),
 (427, datetime.date(2017, 11, 27), Decimal('767.80')),
 (657, datetime.date(2018, 1, 11), Decimal('773.00')),
 (550, datetime.date(2017, 12, 23), Decimal('797.00')),
 (115, datetime.date(2017, 9, 20), Decimal('799.00')),
 (18, datetime.date(2017, 9, 3), Decimal('807.80')),
 (189, datetime.date(2017, 10, 7), Decimal('808.26')),
 (713, datetime.date(2018, 1, 20), Decimal('808.98')),
 (775, datetime.date(2018, 2, 1), Decimal('813.74')),
 (2, datetime.date(2017, 9, 2), Decimal('816.00')),
 (371, datetime.date(2017, 11, 13), Decimal('816.74')),
 (720, datetime.date(2018, 1, 22), Decimal('836.22')),
 (474, datetime.date(2017, 12, 6), Decimal('842.12')),
 (716, datetime.date(2018, 1, 21), Decimal('846.00')),
 (850, datetime.date(2018, 2, 14), Decimal('846.75')),
 (782, datetime.date(2018, 2, 1), Decimal('848.75')),
 (616, datetime.date(2018, 1, 6), Decimal('856.00')),
 (24, datetime.date(2017, 9, 4), Decimal('864.85')),
 (76, datetime.date(2017, 9, 13), Decimal('868.15')),
 (67, datetime.date(2017, 9, 11), Decimal('877.00')),
 (567, datetime.date(2017, 12, 26), Decimal('882.50')),
 (283, datetime.date(2017, 10, 27), Decimal('895.75')),
 (876, datetime.date(2018, 2, 19), Decimal('911.50')),
 (934, datetime.date(2018, 2, 28), Decimal('915.04')),
 (241, datetime.date(2017, 10, 19), Decimal('915.90')),
 (701, datetime.date(2018, 1, 18), Decimal('917.85')),
 (304, datetime.date(2017, 11, 1), Decimal('923.80')),
 (178, datetime.date(2017, 10, 5), Decimal('927.25')),
 (732, datetime.date(2018, 1, 24), Decimal('933.00')),
 (330, datetime.date(2017, 11, 4), Decimal('949.55')),
 (486, datetime.date(2017, 12, 9), Decimal('956.00')),
 (88, datetime.date(2017, 9, 15), Decimal('960.30')),
 (328, datetime.date(2017, 11, 3), Decimal('960.30')),
 (259, datetime.date(2017, 10, 23), Decimal('960.30')),
 (316, datetime.date(2017, 11, 2), Decimal('966.12')),
 (510, datetime.date(2017, 12, 13), Decimal('973.90')),
 (718, datetime.date(2018, 1, 21), Decimal('976.95')),
 (566, datetime.date(2017, 12, 26), Decimal('985.21')),
 (840, datetime.date(2018, 2, 13), Decimal('995.00')),
 (199, datetime.date(2017, 10, 8), Decimal('1002.20')),
 (537, datetime.date(2017, 12, 18), Decimal('1004.05')),
 (401, datetime.date(2017, 11, 21), Decimal('1014.90')),
 (40, datetime.date(2017, 9, 8), Decimal('1018.15')),
 (81, datetime.date(2017, 9, 14), Decimal('1018.50')),
 (452, datetime.date(2017, 12, 1), Decimal('1018.50')),
 (312, datetime.date(2017, 11, 2), Decimal('1019.54')),
 (438, datetime.date(2017, 11, 28), Decimal('1026.40')),
 (155, datetime.date(2017, 9, 30), Decimal('1044.00')),
 (628, datetime.date(2018, 1, 7), Decimal('1047.60')),
 (733, datetime.date(2018, 1, 24), Decimal('1070.80')),
 (311, datetime.date(2017, 11, 2), Decimal('1072.70')),
 (432, datetime.date(2017, 11, 28), Decimal('1088.12')),
 (159, datetime.date(2017, 9, 30), Decimal('1104.60')),
 (475, datetime.date(2017, 12, 7), Decimal('1109.45')),
 (580, datetime.date(2017, 12, 28), Decimal('1112.50')),
 (138, datetime.date(2017, 9, 25), Decimal('1122.70')),
 (811, datetime.date(2018, 2, 8), Decimal('1123.26')),
 (289, datetime.date(2017, 10, 28), Decimal('1123.80')),
 (726, datetime.date(2018, 1, 23), Decimal('1123.97')),
 (240, datetime.date(2017, 10, 19), Decimal('1151.16')),
 (827, datetime.date(2018, 2, 11), Decimal('1159.90')),
 (846, datetime.date(2018, 2, 14), Decimal('1167.88')),
 (603, datetime.date(2018, 1, 2), Decimal('1168.83')),
 (589, datetime.date(2017, 12, 30), Decimal('1169.82')),
 (412, datetime.date(2017, 11, 25), Decimal('1178.58')),
 (515, datetime.date(2017, 12, 13), Decimal('1191.00')),
 (51, datetime.date(2017, 9, 9), Decimal('1200.00')),
 (476, datetime.date(2017, 12, 7), Decimal('1201.00')),
 (517, datetime.date(2017, 12, 14), Decimal('1210.41')),
 (786, datetime.date(2018, 2, 2), Decimal('1216.00')),
 (923, datetime.date(2018, 2, 27), Decimal('1229.30')),
 (868, datetime.date(2018, 2, 17), Decimal('1231.90')),
 (137, datetime.date(2017, 9, 24), Decimal('1235.65')),
 (107, datetime.date(2017, 9, 17), Decimal('1240.40')),
 (192, datetime.date(2017, 10, 7), Decimal('1245.14')),
 (454, datetime.date(2017, 12, 1), Decimal('1248.96')),
 (507, datetime.date(2017, 12, 12), Decimal('1252.71')),
 (346, datetime.date(2017, 11, 8), Decimal('1253.70')),
 (49, datetime.date(2017, 9, 9), Decimal('1254.50')),
 (581, datetime.date(2017, 12, 29), Decimal('1268.98')),
 (586, datetime.date(2017, 12, 30), Decimal('1270.00')),
 (588, datetime.date(2017, 12, 30), Decimal('1271.13')),
 (736, datetime.date(2018, 1, 25), Decimal('1274.55')),
 (723, datetime.date(2018, 1, 22), Decimal('1276.10')),
 (84, datetime.date(2017, 9, 14), Decimal('1278.96')),
 (698, datetime.date(2018, 1, 17), Decimal('1279.98')),
 (261, datetime.date(2017, 10, 23), Decimal('1291.99')),
 (426, datetime.date(2017, 11, 27), Decimal('1294.00')),
 (309, datetime.date(2017, 11, 1), Decimal('1295.90')),
 (627, datetime.date(2018, 1, 7), Decimal('1308.00')),
 (778, datetime.date(2018, 2, 1), Decimal('1314.18')),
 (153, datetime.date(2017, 9, 30), Decimal('1328.95')),
 (62, datetime.date(2017, 9, 11), Decimal('1335.50')),
 (803, datetime.date(2018, 2, 6), Decimal('1342.10')),
 (583, datetime.date(2017, 12, 29), Decimal('1345.22')),
 (357, datetime.date(2017, 11, 11), Decimal('1350.85')),
 (478, datetime.date(2017, 12, 7), Decimal('1352.50')),
 (154, datetime.date(2017, 9, 30), Decimal('1360.05')),
 (667, datetime.date(2018, 1, 12), Decimal('1360.63')),
 (779, datetime.date(2018, 2, 1), Decimal('1388.75')),
 (101, datetime.date(2017, 9, 16), Decimal('1389.64')),
 (572, datetime.date(2017, 12, 27), Decimal('1397.36')),
 (48, datetime.date(2017, 9, 9), Decimal('1397.88')),
 (270, datetime.date(2017, 10, 24), Decimal('1406.98')),
 (681, datetime.date(2018, 1, 14), Decimal('1409.25')),
 (928, datetime.date(2018, 2, 28), Decimal('1444.08')),
 (389, datetime.date(2017, 11, 18), Decimal('1447.30')),
 (927, datetime.date(2018, 2, 28), Decimal('1452.61')),
 (908, datetime.date(2018, 2, 24), Decimal('1459.95')),
 (704, datetime.date(2018, 1, 18), Decimal('1466.75')),
 (932, datetime.date(2018, 2, 28), Decimal('1470.00')),
 (214, datetime.date(2017, 10, 12), Decimal('1470.32')),
 (72, datetime.date(2017, 9, 13), Decimal('1484.13')),
 (8, datetime.date(2017, 9, 2), Decimal('1492.60')),
 (887, datetime.date(2018, 2, 21), Decimal('1493.60')),
 (254, datetime.date(2017, 10, 22), Decimal('1493.75')),
 (851, datetime.date(2018, 2, 14), Decimal('1502.40')),
 (640, datetime.date(2018, 1, 9), Decimal('1529.95')),
 (817, datetime.date(2018, 2, 9), Decimal('1530.90')),
 (231, datetime.date(2017, 10, 16), Decimal('1544.78')),
 (191, datetime.date(2017, 10, 7), Decimal('1552.43')),
 (742, datetime.date(2018, 1, 26), Decimal('1591.82')),
 (670, datetime.date(2018, 1, 13), Decimal('1593.25')),
 (709, datetime.date(2018, 1, 19), Decimal('1633.05')),
 (245, datetime.date(2017, 10, 19), Decimal('1639.77')),
 (555, datetime.date(2017, 12, 24), Decimal('1658.25')),
 (748, datetime.date(2018, 1, 26), Decimal('1663.62')),
 (176, datetime.date(2017, 10, 5), Decimal('1671.53')),
 (232, datetime.date(2017, 10, 16), Decimal('1676.15')),
 (236, datetime.date(2017, 10, 18), Decimal('1678.33')),
 (459, datetime.date(2017, 12, 3), Decimal('1682.62')),
 (440, datetime.date(2017, 11, 29), Decimal('1695.00')),
 (551, datetime.date(2017, 12, 24), Decimal('1696.03')),
 (455, datetime.date(2017, 12, 1), Decimal('1705.78')),
 (376, datetime.date(2017, 11, 14), Decimal('1715.49')),
 (680, datetime.date(2018, 1, 14), Decimal('1716.80')),
 (37, datetime.date(2017, 9, 8), Decimal('1718.78')),
 (536, datetime.date(2017, 12, 18), Decimal('1719.87')),
 (41, datetime.date(2017, 9, 8), Decimal('1723.42')),
 (348, datetime.date(2017, 11, 9), Decimal('1724.07')),
 (795, datetime.date(2018, 2, 4), Decimal('1754.98')),
 (721, datetime.date(2018, 1, 22), Decimal('1755.60')),
 (596, datetime.date(2018, 1, 1), Decimal('1793.45')),
 (756, datetime.date(2018, 1, 29), Decimal('1800.00')),
 (85, datetime.date(2017, 9, 14), Decimal('1807.60')),
 (897, datetime.date(2018, 2, 22), Decimal('1808.64')),
 (916, datetime.date(2018, 2, 25), Decimal('1813.28')),
 (208, datetime.date(2017, 10, 10), Decimal('1828.75')),
 (473, datetime.date(2017, 12, 6), Decimal('1832.18')),
 (719, datetime.date(2018, 1, 21), Decimal('1833.24')),
 (285, datetime.date(2017, 10, 27), Decimal('1836.00')),
 (71, datetime.date(2017, 9, 13), Decimal('1849.80')),
 (453, datetime.date(2017, 12, 1), Decimal('1854.50')),
 (333, datetime.date(2017, 11, 5), Decimal('1854.66')),
 (578, datetime.date(2017, 12, 28), Decimal('1861.62')),
 (585, datetime.date(2017, 12, 30), Decimal('1865.04')),
 (250, datetime.date(2017, 10, 20), Decimal('1867.80')),

In [20]:
%%sql

-- customers and the total $$$ spent

SELECT CustomerID, CustLastName, sum(total_amount) money_spent
FROM customers NATURAL LEFT JOIN (
    SELECT CustomerID, IFNULL(sum(QuotedPrice * QuantityOrdered), 0) as total_amount
    FROM orders NATURAL LEFT JOIN order_details 
    GROUP BY OrderNumber) as q
GROUP BY CustomerID
ORDER BY money_spent DESC

 * mysql://dimitri:***@db.data-science-ust.net
28 rows affected.

[(1012, 'Keyser', Decimal('262174.17')),
 (1017, 'Seidel', Decimal('258544.43')),
 (1005, 'McCrae', Decimal('248250.81')),
 (1006, 'Viescas', Decimal('238622.16')),
 (1025, 'Patterson', Decimal('229550.43')),
 (1013, 'Patterson', Decimal('225582.11')),
 (1004, 'Brown', Decimal('222916.60')),
 (1002, 'Thompson', Decimal('220811.99')),
 (1014, 'Abolrous', Decimal('217587.07')),
 (1020, 'Bonnicksen', Decimal('211354.30')),
 (1024, 'Rosales', Decimal('201535.69')),
 (1026, 'DeGrasse', Decimal('200233.15')),
 (1011, 'Hallmark', Decimal('188026.72')),
 (1010, 'Kennedy', Decimal('186217.65')),
 (1016, 'Wilson', Decimal('180721.12')),
 (1021, 'Pundt', Decimal('178263.45')),
 (1027, 'Patterson', Decimal('178192.81')),
 (1007, 'Sergienko', Decimal('169642.87')),
 (1009, 'Cencini', Decimal('163649.73')),
 (1008, 'Patterson', Decimal('159776.02')),
 (1018, 'Smith', Decimal('142386.71')),
 (1023, 'Schnebly', Decimal('121937.66')),
 (1019, 'Ehrlich', Decimal('113582.59')),
 (1003, 'Hallmark', Decimal('35109.37')),
 (1001, 'Viescas', Decimal('34807.96')),
 (1015, 'Gehring', Decimal('25672.03')),
 (1022, 'Viescas', Decimal('15581.77')),
 (1028, 'Tirekicker', None)]

In [21]:
%%sql

SELECT CustomerID, CustLastName, IFNULL(sum(QuotedPrice * QuantityOrdered), 0) money_spent
FROM customers NATURAL LEFT JOIN (
    SELECT * FROM orders NATURAL JOIN order_details) as q
GROUP BY CustomerID
ORDER BY money_spent DESC

 * mysql://dimitri:***@db.data-science-ust.net
28 rows affected.

[(1012, 'Keyser', Decimal('262174.17')),
 (1017, 'Seidel', Decimal('258544.43')),
 (1005, 'McCrae', Decimal('248250.81')),
 (1006, 'Viescas', Decimal('238622.16')),
 (1025, 'Patterson', Decimal('229550.43')),
 (1013, 'Patterson', Decimal('225582.11')),
 (1004, 'Brown', Decimal('222916.60')),
 (1002, 'Thompson', Decimal('220811.99')),
 (1014, 'Abolrous', Decimal('217587.07')),
 (1020, 'Bonnicksen', Decimal('211354.30')),
 (1024, 'Rosales', Decimal('201535.69')),
 (1026, 'DeGrasse', Decimal('200233.15')),
 (1011, 'Hallmark', Decimal('188026.72')),
 (1010, 'Kennedy', Decimal('186217.65')),
 (1016, 'Wilson', Decimal('180721.12')),
 (1021, 'Pundt', Decimal('178263.45')),
 (1027, 'Patterson', Decimal('178192.81')),
 (1007, 'Sergienko', Decimal('169642.87')),
 (1009, 'Cencini', Decimal('163649.73')),
 (1008, 'Patterson', Decimal('159776.02')),
 (1018, 'Smith', Decimal('142386.71')),
 (1023, 'Schnebly', Decimal('121937.66')),
 (1019, 'Ehrlich', Decimal('113582.59')),
 (1003, 'Hallmark', Decimal('35109.37')),
 (1001, 'Viescas', Decimal('34807.96')),
 (1015, 'Gehring', Decimal('25672.03')),
 (1022, 'Viescas', Decimal('15581.77')),
 (1028, 'Tirekicker', Decimal('0.00'))]

# Summary of principles 
1. Without a `GROUP BY`, aggregation functions collapse the table into a single row.
2. With `GROUP BY`, the grouping attributes become the new primary key of the result.  
3. Do not mix aggregated and non-aggregated values in the result with or without a `GROUP BY`.
4. `HAVING` plays the same role as the `WHERE` clause in a nesting outer query so it can use the output of the aggregation functions.
5. `LEFT JOIN` is often follwed with a `GROUP BY` by the primary key attributes of the left table. In this scenario the entities in the right table are aggregated for each matching row in the left table.